### ISSUE TITLE
Use of ffmpeg to check AAC files causes issues

### ISSUE THREAD

**Issue by kergoth** [geigerzaehler/beets-check#43]
The current code assumes that any external tool can be passed `-v` and will return a zero exit code, but this isn't always true. In this case, it fails to see that ffmpeg is available due to the `-v` check returning an error. I think we should add another optional config item, let the user define the tool availability command / sanity check.

**Comment by geigerzaehler** [comment]
Thanks for bringing this up. I’ve addressed this in #46. Instead of running `ffmpeg -v` to determine whether a checker is available I’m using `shutil.which()`.

Feel free to try this out. I’ll publish a new release next week.
